
from os import listdir
from os.path import isfile, join
import random
import time
import json

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import * 

from jdlv_data import * 
from jdlv_model import *
from jdlv_outils import *

def clean_grid (grid):
    for i in range (default_grid_size):
        for j in range (default_grid_size):
            grid.cases [i][j]['s'] =death_status
            grid.cases [i][j]['c'] = death_color
    return grid

def make_conway (grid, i, j, color):
    try:
        grid = clean_grid (grid)
        cases = grid.cases
        cases [i+2] [j+2] ['s'] = life_status
        cases [i+2] [j+2] ['c'] = "dimgrey"
        cases [i+2] [j+3] ['s'] = life_status
        cases [i+2] [j+3] ['c'] = "dimgrey"
        cases [i+3] [j+1] ['s'] = life_status
        cases [i+3] [j+1] ['c'] = "dimgrey"
        cases [i+4] [j+1] ['s'] = life_status
        cases [i+4] [j+1] ['c'] = "dimgrey"
        cases [i+4] [j+2] ['s'] = life_status
        cases [i+4] [j+2] ['c'] = "dimgrey"
        cases [i+4] [j+3] ['s'] = life_status
        cases [i+4] [j+3] ['c'] = "dimgrey"
        cases [i+5] [j+1] ['s'] = life_status
        cases [i+5] [j+1] ['c'] = "dimgrey"
        cases [i+5] [j+2] ['s'] = life_status
        cases [i+5] [j+2] ['c'] = "dimgrey"
        cases [i+5] [j+3] ['s'] = life_status
        cases [i+5] [j+3] ['c'] = "black"
        cases [i+6] [j+3] ['s'] = life_status
        cases [i+6] [j+3] ['c'] = "black"
        cases [i+7] [j+3] ['s'] = life_status
        cases [i+7] [j+3] ['c'] = "black"
        cases [i+8] [j+3] ['s'] = life_status
        cases [i+8] [j+3] ['c'] = "black"
        cases [i+8] [j+4] ['s'] = life_status
        cases [i+8] [j+4] ['c'] = "black"
        cases [i+9] [j+4] ['s'] = life_status
        cases [i+9] [j+4] ['c'] = "black"
        cases [i+8] [j+5] ['s'] = life_status
        cases [i+8] [j+5] ['c'] = "black"
        cases [i+9] [j+5] ['s'] = life_status
        cases [i+9] [j+5] ['c'] = "black"
        cases [i+6] [j+6] ['s'] = life_status
        cases [i+6] [j+6] ['c'] = "black"
        cases [i+7] [j+6] ['s'] = life_status
        cases [i+7] [j+6] ['c'] = color
        cases [i+8] [j+6] ['s'] = life_status
        cases [i+8] [j+6] ['c'] = "black"
        cases [i+5] [j+7] ['s'] = life_status
        cases [i+5] [j+7] ['c'] = "dimgrey"
        cases [i+8] [j+5] ['s'] = life_status
        cases [i+8] [j+5] ['c'] = "black"
        cases [i+7] [j+6] ['s'] = life_status
        cases [i+7] [j+6] ['c'] = "black"
        cases [i+7] [j+5] ['s'] = life_status
        cases [i+7] [j+5] ['c'] = "gray"
        cases [i+6] [j+5] ['s'] = life_status
        cases [i+6] [j+5] ['c'] = "gray"
        cases [i+6] [j+7] ['s'] = life_status
        cases [i+6] [j+7] ['c'] = "dimgrey"
        cases [i+5] [j+6] ['s'] = life_status
        cases [i+5] [j+6] ['c'] = "dimgrey"
        cases [i+5] [j+5] ['s'] = life_status
        cases [i+5] [j+5] ['c'] = "black"
        cases [i+5] [j+4] ['s'] = life_status
        cases [i+5] [j+4] ['c'] = "black"
        cases [i+6] [j+4] ['s'] = life_status
        cases [i+6] [j+4] ['c'] = "gray"
        cases [i+7] [j+4] ['s'] = life_status
        cases [i+7] [j+4] ['c'] = "gray"
        cases [i+6] [j+8] ['s'] = life_status
        cases [i+6] [j+8] ['c'] = "dimgrey"
        cases [i+6] [j+9] ['s'] = life_status
        cases [i+6] [j+9] ['c'] = "dimgrey"
        cases [i+6] [j+10] ['s'] = life_status
        cases [i+6] [j+10] ['c'] = "dimgrey"
        cases [i+7] [j+11] ['s'] = life_status
        cases [i+7] [j+11] ['c'] = "dimgrey"
        cases [i+7] [j+12] ['s'] = life_status
        cases [i+7] [j+12] ['c'] = "dimgrey"
        cases [i+7] [j+13] ['s'] = life_status
        cases [i+7] [j+13] ['c'] = "dimgrey"
        cases [i+7] [j+14] ['s'] = life_status
        cases [i+7] [j+14] ['c'] = "dimgrey"
        cases [i+7] [j+15] ['s'] = life_status
        cases [i+7] [j+15] ['c'] = "dimgrey"
        cases [i+7] [j+16] ['s'] = life_status
        cases [i+7] [j+16] ['c'] = "dimgrey"
        cases [i+7] [j+17] ['s'] = life_status
        cases [i+7] [j+17] ['c'] = "dimgrey"
        cases [i+6] [j+17] ['s'] = life_status
        cases [i+6] [j+17] ['c'] = "dimgrey"
        cases [i+6] [j+18] ['s'] = life_status
        cases [i+6] [j+18] ['c'] = "dimgrey"
        cases [i+5] [j+18] ['s'] = life_status
        cases [i+5] [j+18] ['c'] = "dimgrey"
        cases [i+5] [j+19] ['s'] = life_status
        cases [i+5] [j+19] ['c'] = "dimgrey"
        cases [i+4] [j+19] ['s'] = life_status
        cases [i+4] [j+19] ['c'] = "dimgrey"
        cases [i+4] [j+20] ['s'] = life_status
        cases [i+4] [j+20] ['c'] = "dimgrey"
        cases [i+4] [j+21] ['s'] = life_status
        cases [i+4] [j+21] ['c'] = "dimgrey"
        cases [i+4] [j+22] ['s'] = life_status
        cases [i+4] [j+22] ['c'] = "dimgrey"
        cases [i+4] [j+23] ['s'] = life_status
        cases [i+4] [j+23] ['c'] = "dimgrey"
        cases [i+4] [j+24] ['s'] = life_status
        cases [i+4] [j+24] ['c'] = "dimgrey"
        cases [i+4] [j+25] ['s'] = life_status
        cases [i+4] [j+25] ['c'] = "silver"
        cases [i+4] [j+26] ['s'] = life_status
        cases [i+4] [j+26] ['c'] = "dimgrey"
        cases [i+4] [j+27] ['s'] = life_status
        cases [i+4] [j+27] ['c'] = "dimgrey"
        cases [i+4] [j+28] ['s'] = life_status
        cases [i+4] [j+28] ['c'] = "dimgrey"
        cases [i+4] [j+18] ['s'] = life_status
        cases [i+4] [j+18] ['c'] = color
        cases [i+4] [j+17] ['s'] = life_status
        cases [i+4] [j+17] ['c'] = color
        cases [i+4] [j+16] ['s'] = life_status
        cases [i+4] [j+16] ['c'] = color
        cases [i+4] [j+16] ['s'] = life_status
        cases [i+4] [j+16] ['c'] = color
        cases [i+4] [j+15] ['s'] = life_status
        cases [i+4] [j+15] ['c'] = "dimgrey"
        cases [i+4] [j+14] ['s'] = life_status
        cases [i+4] [j+14] ['c'] = color
        cases [i+4] [j+13] ['s'] = life_status
        cases [i+4] [j+13] ['c'] = color
        cases [i+4] [j+12] ['s'] = life_status
        cases [i+4] [j+12] ['c'] = color
        cases [i+4] [j+11] ['s'] = life_status
        cases [i+4] [j+11] ['c'] = color
        cases [i+4] [j+10] ['s'] = life_status
        cases [i+4] [j+10] ['c'] = color
        cases [i+4] [j+9] ['s'] = life_status
        cases [i+4] [j+9] ['c'] = color
        cases [i+4] [j+8] ['s'] = life_status
        cases [i+4] [j+8] ['c'] = color
        cases [i+4] [j+7] ['s'] = life_status
        cases [i+4] [j+7] ['c'] = "dimgrey"
        cases [i+4] [j+6] ['s'] = life_status
        cases [i+4] [j+6] ['c'] = "dimgrey"
        cases [i+4] [j+5] ['s'] = life_status
        cases [i+4] [j+5] ['c'] = "dimgrey"
        cases [i+4] [j+4] ['s'] = life_status
        cases [i+4] [j+4] ['c'] = "dimgrey"
        cases [i+5] [j+17] ['s'] = life_status
        cases [i+5] [j+17] ['c'] = color
        cases [i+5] [j+16] ['s'] = life_status
        cases [i+5] [j+16] ['c'] = color
        cases [i+5] [j+16] ['s'] = life_status
        cases [i+5] [j+16] ['c'] = color
        cases [i+5] [j+15] ['s'] = life_status
        cases [i+5] [j+15] ['c'] = color
        cases [i+5] [j+14] ['s'] = life_status
        cases [i+5] [j+14] ['c'] = color
        cases [i+5] [j+13] ['s'] = life_status
        cases [i+5] [j+13] ['c'] = color
        cases [i+5] [j+12] ['s'] = life_status
        cases [i+5] [j+12] ['c'] = color
        cases [i+5] [j+11] ['s'] = life_status
        cases [i+5] [j+11] ['c'] = color
        cases [i+5] [j+10] ['s'] = life_status
        cases [i+5] [j+10] ['c'] = color
        cases [i+5] [j+9] ['s'] = life_status
        cases [i+5] [j+9] ['c'] = color
        cases [i+5] [j+8] ['s'] = life_status
        cases [i+5] [j+8] ['c'] = color
        cases [i+6] [j+14] ['s'] = life_status
        cases [i+6] [j+14] ['c'] = color
        cases [i+6] [j+13] ['s'] = life_status
        cases [i+6] [j+13] ['c'] = color
        cases [i+6] [j+12] ['s'] = life_status
        cases [i+6] [j+12] ['c'] = color
        cases [i+6] [j+11] ['s'] = life_status
        cases [i+6] [j+11] ['c'] = color
        cases [i+6] [j+16] ['s'] = life_status
        cases [i+6] [j+16] ['c'] = color
        cases [i+6] [j+15] ['s'] = life_status
        cases [i+6] [j+15] ['c'] = color
        cases [i+5] [j+27] ['s'] = life_status
        cases [i+5] [j+27] ['c'] = "dimgrey"
        cases [i+5] [j+28] ['s'] = life_status
        cases [i+5] [j+28] ['c'] = "dimgrey"
        cases [i+5] [j+26] ['s'] = life_status
        cases [i+5] [j+26] ['c'] = "black"
        cases [i+5] [j+25] ['s'] = life_status
        cases [i+5] [j+25] ['c'] = "silver"
        cases [i+5] [j+24] ['s'] = life_status
        cases [i+5] [j+24] ['c'] = "dimgrey"
        cases [i+5] [j+23] ['s'] = life_status
        cases [i+5] [j+23] ['c'] = "dimgrey"
        cases [i+3] [j+27] ['s'] = life_status
        cases [i+3] [j+27] ['c'] = "dimgrey"
        cases [i+2] [j+27] ['s'] = life_status
        cases [i+2] [j+27] ['c'] = "yellow"
        cases [i+1] [j+27] ['s'] = life_status
        cases [i+1] [j+27] ['c'] = "yellow"
        cases [i] [j+27] ['s'] = life_status
        cases [i] [j+27] ['c'] = "silver"
        cases [i-1] [j+26] ['s'] = life_status
        cases [i-1] [j+26] ['c'] = "silver"
        cases [i-1] [j+25] ['s'] = life_status
        cases [i-1] [j+25] ['c'] = "silver"
        cases [i-1] [j+24] ['s'] = life_status
        cases [i-1] [j+24] ['c'] = "silver"
        cases [i-1] [j+17] ['s'] = life_status
        cases [i-1] [j+17] ['c'] = "white"
        cases [i-1] [j+18] ['s'] = life_status
        cases [i-1] [j+18] ['c'] = "gray"
        cases [i-2] [j+18] ['s'] = life_status
        cases [i-2] [j+18] ['c'] = "gray"
        cases [i-2] [j+17] ['s'] = life_status
        cases [i-2] [j+17] ['c'] = "white"
        cases [i-3] [j+17] ['s'] = life_status
        cases [i-3] [j+17] ['c'] = "gray"
        cases [i-3] [j+16] ['s'] = life_status
        cases [i-3] [j+16] ['c'] = "white"
        cases [i-4] [j+17] ['s'] = life_status
        cases [i-4] [j+17] ['c'] = "black"
        cases [i-4] [j+16] ['s'] = life_status
        cases [i-4] [j+16] ['c'] = "black"
        cases [i-4] [j+15] ['s'] = life_status
        cases [i-4] [j+15] ['c'] = "black"
        cases [i-4] [j+14] ['s'] = life_status
        cases [i-4] [j+14] ['c'] = "black"
        cases [i-4] [j+13] ['s'] = life_status
        cases [i-4] [j+13] ['c'] = "black"
        cases [i-4] [j+12] ['s'] = life_status
        cases [i-4] [j+12] ['c'] = "black"
        cases [i-4] [j+11] ['s'] = life_status
        cases [i-4] [j+11] ['c'] = "black"
        cases [i-4] [j+10] ['s'] = life_status
        cases [i-4] [j+10] ['c'] = "black"
        cases [i-4] [j+9] ['s'] = life_status
        cases [i-4] [j+9] ['c'] = "black"
        cases [i-4] [j+8] ['s'] = life_status
        cases [i-4] [j+8] ['c'] = "black"
        cases [i-4] [j+7] ['s'] = life_status
        cases [i-4] [j+7] ['c'] = "black"
        cases [i-4] [j+6] ['s'] = life_status
        cases [i-4] [j+6] ['c'] = "black"
        cases [i-3] [j+5] ['s'] = life_status
        cases [i-3] [j+5] ['c'] = "black"
        cases [i-2] [j+5] ['s'] = life_status
        cases [i-2] [j+5] ['c'] = "black"
        cases [i-2] [j+4] ['s'] = life_status
        cases [i-2] [j+4] ['c'] = "black"
        cases [i-1] [j+4] ['s'] = life_status
        cases [i-1] [j+4] ['c'] = "black"
        cases [i] [j+3] ['s'] = life_status
        cases [i] [j+3] ['c'] = color
        cases [i+1] [j+2] ['s'] = life_status
        cases [i+1] [j+2] ['c'] = color
        cases [i] [j+23] ['s'] = life_status
        cases [i] [j+23] ['c'] = "silver"
        cases [i] [j+22] ['s'] = life_status
        cases [i] [j+22] ['c'] = color
        cases [i] [j+21] ['s'] = life_status
        cases [i] [j+21] ['c'] = color
        cases [i] [j+20] ['s'] = life_status
        cases [i] [j+20] ['c'] = color
        cases [i] [j+19] ['s'] = life_status
        cases [i] [j+19] ['c'] = color
        cases [i] [j+18] ['s'] = life_status
        cases [i] [j+18] ['c'] = color
        cases [i] [j+17] ['s'] = life_status
        cases [i] [j+17] ['c'] = color
        cases [i+3] [j+19] ['s'] = life_status
        cases [i+3] [j+19] ['c'] = color
        cases [i+3] [j+20] ['s'] = life_status
        cases [i+3] [j+20] ['c'] = "dimgrey"
        cases [i+3] [j+21] ['s'] = life_status
        cases [i+3] [j+21] ['c'] = "dimgrey"
        cases [i+3] [j+22] ['s'] = life_status
        cases [i+3] [j+22] ['c'] = "dimgrey"
        cases [i+3] [j+23] ['s'] = life_status
        cases [i+3] [j+23] ['c'] = "dimgrey"
        cases [i+3] [j+24] ['s'] = life_status
        cases [i+3] [j+24] ['c'] = "silver"
        cases [i+3] [j+25] ['s'] = life_status
        cases [i+3] [j+25] ['c'] = "silver"
        cases [i+3] [j+26] ['s'] = life_status
        cases [i+3] [j+26] ['c'] = "silver"
        cases [i+3] [j+27] ['s'] = life_status
        cases [i+3] [j+27] ['c'] = "dimgrey"
        cases [i+3] [j+18] ['s'] = life_status
        cases [i+3] [j+18] ['c'] = color
        cases [i+3] [j+17] ['s'] = life_status
        cases [i+3] [j+17] ['c'] = "dimgrey"
        cases [i+3] [j+16] ['s'] = life_status
        cases [i+3] [j+16] ['c'] = color
        cases [i+3] [j+16] ['s'] = life_status
        cases [i+3] [j+16] ['c'] = color
        cases [i+3] [j+15] ['s'] = life_status
        cases [i+3] [j+15] ['c'] = "dimgrey"
        cases [i+3] [j+14] ['s'] = life_status
        cases [i+3] [j+14] ['c'] = color
        cases [i+3] [j+13] ['s'] = life_status
        cases [i+3] [j+13] ['c'] = color
        cases [i+3] [j+12] ['s'] = life_status
        cases [i+3] [j+12] ['c'] = color
        cases [i+3] [j+11] ['s'] = life_status
        cases [i+3] [j+11] ['c'] = color
        cases [i+3] [j+10] ['s'] = life_status
        cases [i+3] [j+10] ['c'] = color
        cases [i+3] [j+9] ['s'] = life_status
        cases [i+3] [j+9] ['c'] = color
        cases [i+3] [j+8] ['s'] = life_status
        cases [i+3] [j+8] ['c'] = color
        cases [i+3] [j+7] ['s'] = life_status
        cases [i+3] [j+7] ['c'] = color
        cases [i+3] [j+6] ['s'] = life_status
        cases [i+3] [j+6] ['c'] = "dimgrey"
        cases [i+3] [j+5] ['s'] = life_status
        cases [i+3] [j+5] ['c'] = "dimgrey"
        cases [i+3] [j+4] ['s'] = life_status
        cases [i+3] [j+4] ['c'] = "dimgrey"
        cases [i+3] [j+3] ['s'] = life_status
        cases [i+3] [j+3] ['c'] = "dimgrey"
        cases [i+3] [j+2] ['s'] = life_status
        cases [i+3] [j+2] ['c'] = "dimgrey"
        cases [i+2] [j+19] ['s'] = life_status
        cases [i+2] [j+19] ['c'] = "dimgrey"
        cases [i+2] [j+20] ['s'] = life_status
        cases [i+2] [j+20] ['c'] = color
        cases [i+2] [j+21] ['s'] = life_status
        cases [i+2] [j+21] ['c'] = color
        cases [i+2] [j+22] ['s'] = life_status
        cases [i+2] [j+22] ['c'] = color
        cases [i+2] [j+23] ['s'] = life_status
        cases [i+2] [j+23] ['c'] = "yellow"
        cases [i+2] [j+24] ['s'] = life_status
        cases [i+2] [j+24] ['c'] = "yellow"
        cases [i+2] [j+25] ['s'] = life_status
        cases [i+2] [j+25] ['c'] = "silver"
        cases [i+2] [j+26] ['s'] = life_status
        cases [i+2] [j+26] ['c'] = "yellow"
        cases [i+2] [j+27] ['s'] = life_status
        cases [i+2] [j+27] ['c'] = "yellow"
        cases [i+2] [j+18] ['s'] = life_status
        cases [i+2] [j+18] ['c'] = color
        cases [i+2] [j+17] ['s'] = life_status
        cases [i+2] [j+17] ['c'] = "dimgrey"
        cases [i+2] [j+16] ['s'] = life_status
        cases [i+2] [j+16] ['c'] = color
        cases [i+2] [j+16] ['s'] = life_status
        cases [i+2] [j+16] ['c'] = color
        cases [i+2] [j+15] ['s'] = life_status
        cases [i+2] [j+15] ['c'] = "dimgrey"
        cases [i+2] [j+14] ['s'] = life_status
        cases [i+2] [j+14] ['c'] = color
        cases [i+2] [j+13] ['s'] = life_status
        cases [i+2] [j+13] ['c'] = color
        cases [i+2] [j+12] ['s'] = life_status
        cases [i+2] [j+12] ['c'] = color
        cases [i+2] [j+11] ['s'] = life_status
        cases [i+2] [j+11] ['c'] = color
        cases [i+2] [j+10] ['s'] = life_status
        cases [i+2] [j+10] ['c'] = color
        cases [i+2] [j+9] ['s'] = life_status
        cases [i+2] [j+9] ['c'] = color
        cases [i+2] [j+8] ['s'] = life_status
        cases [i+2] [j+8] ['c'] = color
        cases [i+2] [j+7] ['s'] = life_status
        cases [i+2] [j+7] ['c'] = color
        cases [i+2] [j+6] ['s'] = life_status
        cases [i+2] [j+6] ['c'] = color
        cases [i+2] [j+5] ['s'] = life_status
        cases [i+2] [j+5] ['c'] = "dimgrey"
        cases [i+2] [j+4] ['s'] = life_status
        cases [i+2] [j+4] ['c'] = "dimgrey"
        cases [i+1] [j+19] ['s'] = life_status
        cases [i+1] [j+19] ['c'] = color
        cases [i+1] [j+20] ['s'] = life_status
        cases [i+1] [j+20] ['c'] = color
        cases [i+1] [j+21] ['s'] = life_status
        cases [i+1] [j+21] ['c'] = color
        cases [i+1] [j+22] ['s'] = life_status
        cases [i+1] [j+22] ['c'] = color
        cases [i+1] [j+23] ['s'] = life_status
        cases [i+1] [j+23] ['c'] = "yellow"
        cases [i+1] [j+24] ['s'] = life_status
        cases [i+1] [j+24] ['c'] = "yellow"
        cases [i+1] [j+25] ['s'] = life_status
        cases [i+1] [j+25] ['c'] = "silver"
        cases [i+1] [j+26] ['s'] = life_status
        cases [i+1] [j+26] ['c'] = "yellow"
        cases [i+1] [j+27] ['s'] = life_status
        cases [i+1] [j+27] ['c'] = "yellow"
        cases [i+1] [j+18] ['s'] = life_status
        cases [i+1] [j+18] ['c'] = color
        cases [i+1] [j+17] ['s'] = life_status
        cases [i+1] [j+17] ['c'] = color
        cases [i+1] [j+16] ['s'] = life_status
        cases [i+1] [j+16] ['c'] = color
        cases [i+1] [j+16] ['s'] = life_status
        cases [i+1] [j+16] ['c'] = color
        cases [i+1] [j+15] ['s'] = life_status
        cases [i+1] [j+15] ['c'] = color
        cases [i+1] [j+14] ['s'] = life_status
        cases [i+1] [j+14] ['c'] = color
        cases [i+1] [j+13] ['s'] = life_status
        cases [i+1] [j+13] ['c'] = color
        cases [i+1] [j+12] ['s'] = life_status
        cases [i+1] [j+12] ['c'] = color
        cases [i+1] [j+11] ['s'] = life_status
        cases [i+1] [j+11] ['c'] = color
        cases [i+1] [j+10] ['s'] = life_status
        cases [i+1] [j+10] ['c'] = color
        cases [i+1] [j+9] ['s'] = life_status
        cases [i+1] [j+9] ['c'] = color
        cases [i+1] [j+8] ['s'] = life_status
        cases [i+1] [j+8] ['c'] = color
        cases [i+1] [j+7] ['s'] = life_status
        cases [i+1] [j+7] ['c'] = color
        cases [i+1] [j+6] ['s'] = life_status
        cases [i+1] [j+6] ['c'] = color
        cases [i+1] [j+5] ['s'] = life_status
        cases [i+1] [j+5] ['c'] = color
        cases [i+1] [j+4] ['s'] = life_status
        cases [i+1] [j+4] ['c'] = color
        cases [i+1] [j+3] ['s'] = life_status
        cases [i+1] [j+3] ['c'] = color
        cases [i] [j+19] ['s'] = life_status
        cases [i] [j+19] ['c'] = color
        cases [i] [j+20] ['s'] = life_status
        cases [i] [j+20] ['c'] = color
        cases [i] [j+21] ['s'] = life_status
        cases [i] [j+21] ['c'] = color
        cases [i] [j+22] ['s'] = life_status
        cases [i] [j+22] ['c'] = color
        cases [i] [j+23] ['s'] = life_status
        cases [i] [j+23] ['c'] = "silver"
        cases [i] [j+24] ['s'] = life_status
        cases [i] [j+24] ['c'] = "silver"
        cases [i] [j+25] ['s'] = life_status
        cases [i] [j+25] ['c'] = "silver"
        cases [i] [j+26] ['s'] = life_status
        cases [i] [j+26] ['c'] = "silver"
        cases [i] [j+27] ['s'] = life_status
        cases [i] [j+27] ['c'] = "silver"
        cases [i] [j+18] ['s'] = life_status
        cases [i] [j+18] ['c'] = color
        cases [i] [j+17] ['s'] = life_status
        cases [i] [j+17] ['c'] = color
        cases [i] [j+16] ['s'] = life_status
        cases [i] [j+16] ['c'] = color
        cases [i] [j+16] ['s'] = life_status
        cases [i] [j+16] ['c'] = color
        cases [i] [j+15] ['s'] = life_status
        cases [i] [j+15] ['c'] = color
        cases [i] [j+14] ['s'] = life_status
        cases [i] [j+14] ['c'] = "white"
        cases [i] [j+13] ['s'] = life_status
        cases [i] [j+13] ['c'] = "white"
        cases [i] [j+12] ['s'] = life_status
        cases [i] [j+12] ['c'] = "gray"
        cases [i] [j+11] ['s'] = life_status
        cases [i] [j+11] ['c'] = "gray"
        cases [i] [j+10] ['s'] = life_status
        cases [i] [j+10] ['c'] = "gray"
        cases [i] [j+9] ['s'] = life_status
        cases [i] [j+9] ['c'] = "gray"
        cases [i] [j+8] ['s'] = life_status
        cases [i] [j+8] ['c'] = "gray"
        cases [i] [j+7] ['s'] = life_status
        cases [i] [j+7] ['c'] = "black"
        cases [i] [j+6] ['s'] = life_status
        cases [i] [j+6] ['c'] = "black"
        cases [i] [j+5] ['s'] = life_status
        cases [i] [j+5] ['c'] = "black"
        cases [i] [j+4] ['s'] = life_status
        cases [i] [j+4] ['c'] = "black"
        cases [i-1] [j+16] ['c'] = color
        cases [i-1] [j+16] ['s'] = life_status
        cases [i-1] [j+16] ['c'] = "white"
        cases [i-1] [j+15] ['s'] = life_status
        cases [i-1] [j+15] ['c'] = "white"
        cases [i-1] [j+14] ['s'] = life_status
        cases [i-1] [j+14] ['c'] = "white"
        cases [i-1] [j+13] ['s'] = life_status
        cases [i-1] [j+13] ['c'] = "white"
        cases [i-1] [j+12] ['s'] = life_status
        cases [i-1] [j+12] ['c'] = "gray"
        cases [i-1] [j+11] ['s'] = life_status
        cases [i-1] [j+11] ['c'] = "white"
        cases [i-1] [j+10] ['s'] = life_status
        cases [i-1] [j+10] ['c'] = "white"
        cases [i-1] [j+9] ['s'] = life_status
        cases [i-1] [j+9] ['c'] = "white"
        cases [i-1] [j+8] ['s'] = life_status
        cases [i-1] [j+8] ['c'] = "black"
        cases [i-1] [j+7] ['s'] = life_status
        cases [i-1] [j+7] ['c'] = "black"
        cases [i-1] [j+6] ['s'] = life_status
        cases [i-1] [j+6] ['c'] = "gray"
        cases [i-1] [j+5] ['s'] = life_status
        cases [i-1] [j+5] ['c'] = "gray"
        cases [i-2] [j+16] ['c'] = color
        cases [i-2] [j+16] ['s'] = life_status
        cases [i-2] [j+16] ['c'] = "white"
        cases [i-2] [j+15] ['s'] = life_status
        cases [i-2] [j+15] ['c'] = "white"
        cases [i-2] [j+14] ['s'] = life_status
        cases [i-2] [j+14] ['c'] = "white"
        cases [i-2] [j+13] ['s'] = life_status
        cases [i-2] [j+13] ['c'] = "white"
        cases [i-2] [j+12] ['s'] = life_status
        cases [i-2] [j+12] ['c'] = "gray"
        cases [i-2] [j+11] ['s'] = life_status
        cases [i-2] [j+11] ['c'] = "white"
        cases [i-2] [j+10] ['s'] = life_status
        cases [i-2] [j+10] ['c'] = "white"
        cases [i-2] [j+9] ['s'] = life_status
        cases [i-2] [j+9] ['c'] = "white"
        cases [i-2] [j+8] ['s'] = life_status
        cases [i-2] [j+8] ['c'] = "black"
        cases [i-2] [j+7] ['s'] = life_status
        cases [i-2] [j+7] ['c'] = "black"
        cases [i-2] [j+6] ['s'] = life_status
        cases [i-2] [j+6] ['c'] = "gray"
        cases [i-3] [j+15] ['s'] = life_status
        cases [i-3] [j+15] ['c'] = "white"
        cases [i-3] [j+14] ['s'] = life_status
        cases [i-3] [j+14] ['c'] = "white"
        cases [i-3] [j+13] ['s'] = life_status
        cases [i-3] [j+13] ['c'] = "white"
        cases [i-3] [j+12] ['s'] = life_status
        cases [i-3] [j+12] ['c'] = "gray"
        cases [i-3] [j+11] ['s'] = life_status
        cases [i-3] [j+11] ['c'] = "white"
        cases [i-3] [j+10] ['s'] = life_status
        cases [i-3] [j+10] ['c'] = "white"
        cases [i-3] [j+9] ['s'] = life_status
        cases [i-3] [j+9] ['c'] = "white"
        cases [i-3] [j+8] ['s'] = life_status
        cases [i-3] [j+8] ['c'] = "black"
        cases [i-3] [j+7] ['s'] = life_status
        cases [i-3] [j+7] ['c'] = "gray"
        cases [i-3] [j+6] ['s'] = life_status
        cases [i-3] [j+6] ['c'] = "gray"
        cases [i+5] [j+20] ['s'] = life_status
        cases [i+5] [j+20] ['c'] = "black"
        cases [i+5] [j+21] ['s'] = life_status
        cases [i+5] [j+21] ['c'] = "black"
        cases [i+5] [j+22] ['s'] = life_status
        cases [i+5] [j+22] ['c'] = "black"
        cases [i+6] [j+19] ['s'] = life_status
        cases [i+6] [j+19] ['c'] = "black"
        cases [i+6] [j+20] ['s'] = life_status
        cases [i+6] [j+20] ['c'] = "black"
        cases [i+6] [j+21] ['s'] = life_status
        cases [i+6] [j+21] ['c'] = "black"
        cases [i+6] [j+22] ['s'] = life_status
        cases [i+6] [j+22] ['c'] = "black"
        cases [i+6] [j+23] ['s'] = life_status
        cases [i+6] [j+23] ['c'] = "black"
        cases [i+7] [j+19] ['s'] = life_status
        cases [i+7] [j+19] ['c'] = "black"
        cases [i+7] [j+20] ['s'] = life_status
        cases [i+7] [j+20] ['c'] = "dimgrey"
        cases [i+7] [j+21] ['s'] = life_status
        cases [i+7] [j+21] ['c'] = "dimgrey"
        cases [i+7] [j+22] ['s'] = life_status
        cases [i+7] [j+22] ['c'] = "black"
        cases [i+7] [j+23] ['s'] = life_status
        cases [i+7] [j+23] ['c'] = "black"
        cases [i+7] [j+24] ['s'] = life_status
        cases [i+7] [j+24] ['c'] = "black"
        cases [i+7] [j+25] ['s'] = life_status
        cases [i+7] [j+25] ['c'] = "black"
        cases [i+7] [j+26] ['s'] = life_status
        cases [i+7] [j+26] ['c'] = "black"
        cases [i+7] [j+27] ['s'] = life_status
        cases [i+7] [j+27] ['c'] = "black"
        cases [i+5] [j+26] ['s'] = life_status
        cases [i+5] [j+26] ['c'] = "black"
        cases [i+6] [j+26] ['s'] = life_status
        cases [i+6] [j+26] ['c'] = "black"
        cases [i+6] [j+27] ['s'] = life_status
        cases [i+6] [j+27] ['c'] = "black"
        cases [i+8] [j+26] ['s'] = life_status
        cases [i+8] [j+26] ['c'] = "black"
        cases [i+8] [j+25] ['s'] = life_status
        cases [i+8] [j+25] ['c'] = "black"
        cases [i+8] [j+19] ['s'] = life_status
        cases [i+8] [j+19] ['c'] = "black"
        cases [i+8] [j+20] ['s'] = life_status
        cases [i+8] [j+20] ['c'] = "dimgrey"
        cases [i+8] [j+21] ['s'] = life_status
        cases [i+8] [j+21] ['c'] = "dimgrey"
        cases [i+8] [j+22] ['s'] = life_status
        cases [i+8] [j+22] ['c'] = "black"
        cases [i+8] [j+23] ['s'] = life_status
        cases [i+8] [j+23] ['c'] = "black"
        cases [i+9] [j+19] ['s'] = life_status
        cases [i+9] [j+19] ['c'] = "black"
        cases [i+9] [j+20] ['s'] = life_status
        cases [i+9] [j+20] ['c'] = "black"
        cases [i+9] [j+21] ['s'] = life_status
        cases [i+9] [j+21] ['c'] = "black"
        cases [i+9] [j+22] ['s'] = life_status
        cases [i+9] [j+22] ['c'] = "black"
        cases [i+9] [j+23] ['s'] = life_status
        cases [i+9] [j+23] ['c'] = "black"
        cases [i+10] [j+20] ['s'] = life_status
        cases [i+10] [j+20] ['c'] = "black"
        cases [i+10] [j+21] ['s'] = life_status
        cases [i+10] [j+21] ['c'] = "black"
        cases [i+10] [j+22] ['s'] = life_status
        cases [i+10] [j+22] ['c'] = "black"
        cases [i+6] [j+24] ['s'] = life_status
        cases [i+6] [j+24] ['c'] = "silver"
        cases [i+6] [j+25] ['s'] = life_status
        cases [i+6] [j+25] ['c'] = "silver"

        
    except:
        pass
    return grid
       
def make_scooter (grid, i, j, color) :     
    try :
        cases = grid.cases
        cases [i] [j+70]['s']=life_status
        cases [i] [j+70] ['c'] = 'red'
        cases [i] [j+71]['s']=life_status
        cases [i] [j+71] ['c'] = 'black'
        cases [i] [j+72]['s']=life_status
        cases [i] [j+72] ['c'] = 'black'
        cases [i] [j+73]['s']=life_status
        cases [i] [j+73] ['c'] = 'grey'
        cases [i] [j+74]['s']=life_status
        cases [i] [j+74] ['c'] = 'black'
        cases [i] [j+75]['s']=life_status
        cases [i] [j+75] ['c'] = 'black'
        cases [i] [j+76]['s']=life_status
        cases [i] [j+76] ['c'] = 'red'
        cases [i] [j+77]['s']=life_status
        cases [i] [j+77] ['c'] = 'red'
        cases [i] [j+78]['s']=life_status
        cases [i] [j+78] ['c'] = 'red'
        cases [i] [j+79]['s']=life_status
        cases [i] [j+79] ['c'] = 'red'
        cases [i] [j+80]['s']=life_status
        cases [i] [j+80] ['c'] = 'black'
        cases [i] [j+81]['s']=life_status
        cases [i] [j+81] ['c'] = 'black'
        cases [i] [j+82]['s']=life_status
        cases [i] [j+82] ['c'] = 'grey'
        cases [i] [j+83]['s']=life_status
        cases [i] [j+83] ['c'] = 'black'
        cases [i] [j+84]['s']=life_status
        cases [i] [j+84] ['c'] = 'black'
        cases [i] [j+85]['s']=life_status
        cases [i] [j+85] ['c'] = 'red'
        cases [i] [j+86]['s']=life_status
        cases [i] [j+86] ['c'] = 'red'
        cases [i-1] [j+70]['s']=life_status
        cases [i-1] [j+70] ['c'] = 'red'
        cases [i-1] [j+71]['s']=life_status
        cases [i-1] [j+71] ['c'] = 'red'
        cases [i-1] [j+72]['s']=life_status
        cases [i-1] [j+72] ['c'] = color
        cases [i-1] [j+73]['s']=life_status
        cases [i-1] [j+73] ['c'] = color
        cases [i-1] [j+74]['s']=life_status
        cases [i-1] [j+74] ['c'] = color
        cases [i-1] [j+75]['s']=life_status
        cases [i-1] [j+75] ['c'] = 'red'
        cases [i-1] [j+76]['s']=life_status
        cases [i-1] [j+76] ['c'] = 'red'
        cases [i-1] [j+77]['s']=life_status
        cases [i-1] [j+77] ['c'] = 'red'
        cases [i-1] [j+78]['s']=life_status
        cases [i-1] [j+78] ['c'] = 'red'
        cases [i-1] [j+79]['s']=life_status
        cases [i-1] [j+79] ['c'] = 'red'
        cases [i-1] [j+80]['s']=life_status
        cases [i-1] [j+80] ['c'] = 'red'
        cases [i-1] [j+81]['s']=life_status
        cases [i-1] [j+81] ['c'] = color
        cases [i-1] [j+82]['s']=life_status
        cases [i-1] [j+82] ['c'] = color
        cases [i-1] [j+83]['s']=life_status
        cases [i-1] [j+83] ['c'] = color
        cases [i-1] [j+84]['s']=life_status
        cases [i-1] [j+84] ['c'] = 'red'
        cases [i-1] [j+85]['s']=life_status
        cases [i-1] [j+85] ['c'] = 'red'
        cases [i-1] [j+86]['s']=life_status
        cases [i-1] [j+86] ['c'] = 'red'
        
        cases [i-2] [j+71]['s']=life_status
        cases [i-2] [j+71] ['c'] = 'red'
        cases [i-2] [j+72]['s']=life_status
        cases [i-2] [j+72] ['c'] = 'red'
        cases [i-2] [j+73]['s']=life_status
        cases [i-2] [j+73] ['c'] = 'red'
        cases [i-2] [j+74]['s']=life_status
        cases [i-2] [j+74] ['c'] = 'red'
        cases [i-2] [j+75]['s']=life_status
        cases [i-2] [j+75] ['c'] = 'red'
        cases [i-2] [j+76]['s']=life_status
        cases [i-2] [j+76] ['c'] = 'silver'
        cases [i-2] [j+77]['s']=life_status
        cases [i-2] [j+77] ['c'] = 'silver'
        cases [i-2] [j+78]['s']=life_status
        cases [i-2] [j+78] ['c'] ='silver'
        cases [i-2] [j+79]['s']=life_status
        cases [i-2] [j+79] ['c'] = 'red'
        cases [i-2] [j+80]['s']=life_status
        cases [i-2] [j+80] ['c'] = 'red'
        cases [i-2] [j+81]['s']=life_status
        cases [i-2] [j+81] ['c'] = 'red'
        cases [i-2] [j+82]['s']=life_status
        cases [i-2] [j+82] ['c'] = 'red'
        cases [i-2] [j+83]['s']=life_status
        cases [i-2] [j+83] ['c'] = 'red'
        cases [i-2] [j+84]['s']=life_status
        cases [i-2] [j+84] ['c'] = 'red'
        cases [i-2] [j+85]['s']=life_status
        cases [i-2] [j+85] ['c'] = 'red'
        
        cases [i-3] [j+72]['s']=life_status
        cases [i-3] [j+72] ['c'] = 'red'
        cases [i-3] [j+73]['s']=life_status
        cases [i-3] [j+73] ['c'] = 'red'
        cases [i-3] [j+74]['s']=life_status
        cases [i-3] [j+74] ['c'] ='silver'
        cases [i-3] [j+75]['s']=life_status
        cases [i-3] [j+75] ['c'] = 'silver'
        cases [i-3] [j+80]['s']=life_status
        cases [i-3] [j+80] ['c'] = 'black'
        cases [i-3] [j+81]['s']=life_status
        cases [i-3] [j+81] ['c'] = 'red'
        cases [i-3] [j+82]['s']=life_status
        cases [i-3] [j+82] ['c'] = 'red'
        cases [i-3] [j+83]['s']=life_status
        cases [i-3] [j+83] ['c'] = 'red'
        cases [i-3] [j+84]['s']=life_status
        cases [i-3] [j+84] ['c'] = 'red'
        cases [i-3] [j+85]['s']=life_status
        cases [i-3] [j+85] ['c'] = 'black'
       
        cases [i-4] [j+73]['s']=life_status
        cases [i-4] [j+73] ['c'] = 'red'
        cases [i-4] [j+74]['s']=life_status
        cases [i-4] [j+74] ['c'] = 'red'
        cases [i-4] [j+75]['s']=life_status
        cases [i-4] [j+75] ['c'] = 'silver'
        cases [i-4] [j+81]['s']=life_status
        cases [i-4] [j+81] ['c'] = 'black'
        cases [i-4] [j+82]['s']=life_status
        cases [i-4] [j+82] ['c'] = 'black'
        cases [i-4] [j+83]['s']=life_status
        cases [i-4] [j+83] ['c'] = 'black'
        cases [i-4] [j+84]['s']=life_status
        cases [i-4] [j+84] ['c'] = 'black'
        
        cases [i-5] [j+74]['s']=life_status
        cases [i-5] [j+74] ['c'] = 'red'
        cases [i-5] [j+75]['s']=life_status
        cases [i-5] [j+75] ['c'] = 'red'
        cases [i-5] [j+76]['s']=life_status
        cases [i-5] [j+76] ['c'] = 'silver'
        
        cases [i-6] [j+74]['s']=life_status
        cases [i-6] [j+74] ['c'] = 'red'
        cases [i-6] [j+75]['s']=life_status
        cases [i-6] [j+75] ['c'] = 'red'
        cases [i-6] [j+76]['s']=life_status
        cases [i-6] [j+76] ['c'] = 'red'
        cases [i-6] [j+77]['s']=life_status
        cases [i-6] [j+77] ['c'] = 'red'
        
        cases [i-7] [j+74]['s']=life_status
        cases [i-7] [j+74] ['c'] = 'yellow'
        cases [i-7] [j+75]['s']=life_status
        cases [i-7] [j+75] ['c'] = 'yellow'
        cases [i-7] [j+76]['s']=life_status
        cases [i-7] [j+76] ['c'] = 'red'
        cases [i-7] [j+77]['s']=life_status
        cases [i-7] [j+77] ['c'] = 'black'
        cases [i-7] [j+78]['s']=life_status
        cases [i-7] [j+78] ['c'] = 'black'
        
        cases [i-8] [j+75]['s']=life_status
        cases [i-8] [j+75] ['c'] = 'red'
        cases [i-8] [j+76]['s']=life_status
        cases [i-8] [j+76] ['c'] = 'red'
        
        cases [i+1] [j+71]['s']=life_status
        cases [i+1] [j+71] ['c'] = 'black'
        cases [i+2] [j+71]['s']=life_status
        cases [i+2] [j+71] ['c'] = 'black'
        cases [i+1] [j+72]['s']=life_status
        cases [i+1] [j+72] ['c'] = 'grey'
        cases [i+2] [j+72]['s']=life_status
        cases [i+2] [j+72] ['c'] = 'black'
        cases [i+1] [j+73]['s']=life_status
        cases [i+1] [j+73] ['c'] = 'grey'
        cases [i+2] [j+73]['s']=life_status
        cases [i+2] [j+73] ['c'] = 'grey'
        cases [i+1] [j+74]['s']=life_status
        cases [i+1] [j+74] ['c'] = 'grey'
        cases [i+2] [j+74]['s']=life_status
        cases [i+2] [j+74] ['c'] = 'black'
        cases [i+1] [j+75]['s']=life_status
        cases [i+1] [j+75] ['c'] = color
        cases [i+2] [j+75]['s']=life_status
        cases [i+2] [j+75] ['c'] = 'black'
        cases [i+3] [j+72]['s']=life_status
        cases [i+3] [j+72] ['c'] = 'black'
        cases [i+3] [j+73]['s']=life_status
        cases [i+3] [j+73] ['c'] = 'black'
        cases [i+3] [j+74]['s']=life_status
        cases [i+3] [j+74] ['c'] = 'black'
        
        cases [i+1] [j+80]['s']=life_status
        cases [i+1] [j+80] ['c'] = 'black'
        cases [i+2] [j+80]['s']=life_status
        cases [i+2] [j+80] ['c'] = 'black'
        cases [i+1] [j+81]['s']=life_status
        cases [i+1] [j+81] ['c'] = 'grey'
        cases [i+2] [j+81]['s']=life_status
        cases [i+2] [j+81] ['c'] = 'black'
        cases [i+1] [j+82]['s']=life_status
        cases [i+1] [j+82] ['c'] = 'grey'
        cases [i+2] [j+82]['s']=life_status
        cases [i+2] [j+82] ['c'] = 'grey'
        cases [i+1] [j+83]['s']=life_status
        cases [i+1] [j+83] ['c'] = 'grey'
        cases [i+2] [j+83]['s']=life_status
        cases [i+2] [j+83] ['c'] = 'black'
        cases [i+1] [j+84]['s']=life_status
        cases [i+1] [j+84] ['c'] = 'black'
        cases [i+2] [j+84]['s']=life_status
        cases [i+2] [j+84] ['c'] = 'black'
        cases [i+3] [j+81]['s']=life_status
        cases [i+3] [j+81] ['c'] = 'black'
        cases [i+3] [j+82]['s']=life_status
        cases [i+3] [j+82] ['c'] = 'black'
        cases [i+3] [j+83]['s']=life_status
        cases [i+3] [j+83] ['c'] = 'black'
    except:
        pass
    return grid


    
def apply_game_of_life_rules (grid):
    previous_grid = grid
    previous_cases = previous_grid.cases
    cases = grid.cases # cases is a list of lists of dictionnaries
    next_grid = Grid (len (cases))
    next_cases = next_grid.cases
    for i in range (1, len (cases) - 1):
        for j in range (1, len (cases) - 1):
            previous_status = cases [i][j]['s']
            voisins = get_voisins (cases, i, j)
            nbre_alive_voisins = count_alive_voisins (voisins)
            if nbre_alive_voisins == 3 or nbre_alive_voisins==2:
                next_cases [i] [j] = revive_case (next_cases [i] [j])
            elif nbre_alive_voisins <= 1 or nbre_alive_voisins >= 4:
                next_cases [i] [j] = kill_case (next_cases [i] [j])
            else:
                next_cases [i] [j] = cases [i] [j]
    return next_grid

def apply_rules (grid, compteur):
    next_grid = grid
    if -1 <compteur< 22 :
        if compteur % 1 == 0:
            next_grid = \
                make_conway (grid, 14, compteur, 'red') 
            next_grid = \
                make_scooter(grid, 21, - compteur,'red' )
    else:
        print("hi")
        time.sleep(0.01)
        next_grid = apply_game_of_life_rules (grid)
    return next_grid